Add controllers
AleksKras/java-shareit pull request #1
Opened 2022-10-22 19:01 UTC by AleksKras

2022-10-24 16:01 UTC, Frilock requested changes
Добрый день, написал ряд комментариев к Вашему коду. Жду новую версию, будут вопросы приходите.

2022-10-24 16:01 UTC, Frilock commented on pom.xml
> +			<version>1.4.2.Final</version>
Вы версию указываете <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>, а тут опять цифрами пишите =)

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    /*
Давайте закомментированный код не будем оставлять

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +@Data
Зачем тут эта аннотация?

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +        if (!query.isEmpty()) {
я так понимаю, что query может прийти null? Если да, то получите NPE. Чтобы избегать таких ситуаций можете использовать StringUtils.isNotBlank

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +            searchResultList = items.stream().filter(item ->
Лучше так 
stream()
.filter(...)
...
.collect()

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private ItemMapper mapper;
А разве ItemMapper не является компонентом спринга?

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +
Лишняя пустая строка

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +@Slf4j
Лишняя аннотация, в данном классе логгер не используется

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +@Data
Для чего тут эта аннотация?)

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            if (mapUser.getEmail().equals(email) && mapUser.getId() != userId) {
email может быть null? Если да, то советую использовать null safe equals - Objects.equals(o1, o2)

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    @Autowired
У Вас над классом стоит AllArgsConstructor, это значит, что lombok сгенерирует Вам конструктор, а спринг сам заинжектит бины. 
Аннотация Autowired над полями класса является устаревшей практикой, правильно инжектить бины либо через конструктор, либо через set метод. В вашем же случае, ломбок сгенерирует конструктор - поэтому аннотация над полями не нужна. Стоит тут разобраться по лучше, поскольку это 1 из самых частых вопросов на собеседованиях.
Кроме того, если поля класса инжектятся только через конструктор, то переменные можно сделать final

Еще советую установить в IDEA плагин sonarlint - это статический анализатор кода, он покажет ряд хороших практик и подсветит возможные ошибки.

2022-10-24 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public User create(User user) {
Вообще считается что если Вы реализуете какой то метод интерфейса, то над методом надо ставить override

2022-10-25 16:00 UTC, Frilock requested changes
Добрый вечер, в целом ок, но все таки пару комментариев я оставил. Думаю, что вы просто не заметили пару мест. Давайте поправим

2022-10-25 16:00 UTC, Frilock commented on pom.xml
> +			<version>2.5</version>
Опять же давайте по аналогии с другими библиотеками поместим в properties

2022-10-25 16:00 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemService.checkItemOwner(id, userId);
По хорошему, раз вы решили логгировать на уровне контроллера запросы то и тут следовало бы

2022-10-25 16:00 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +    private long id;
А проинициализировать не нужно?

2022-10-25 16:00 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserDaoImpl.java
> +    public User create(@Valid User user) {
Override над методами для единообразия давайте проставим. Проверьте другие места тоже

2022-10-25 16:00 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            if (StringUtils.equalsIgnoreCase(mapUser.getEmail(),email) && mapUser.getId() != userId) {
пробел перед email

2022-10-25 17:44 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/item/ItemDaoImpl.java
> +    private long id;
так примитив long по умолчанию равен 0. на мой взгляд дополнительная инициализация избыточна

2022-10-25 18:41 UTC, Frilock approved these changes
Принято

2022-11-02 18:05 UTC, merged