Add item requests
AleksKras/java-shareit pull request #3
Opened 2022-11-22 20:21 UTC by AleksKras

2022-11-23 17:19 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую версию.

2022-11-23 17:19 UTC, Frilock commented on pom.xml
> +					<source>9</source>
А зачем вы версию поменяли? У вас по ТЗ все должно на 8й версии работать, если мне память не изменяет

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                         @RequestParam(value = "state", required = false) Optional<String> state,
А зачем все в Optional тут обернули? Мне даже интересно стало, я просто лично сам так не делал. Если null передать, то будет Optional.empty?

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findByBookerEquals(User user, Pageable pageable);
List<Booking> findByBookerEquals(User user);

    Page<Booking> findByBookerEquals(User user, Pageable pageable);
    
    Мне кажется должен оставаться один метод с Page. Зачем второй? Логики не очень понял.

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(" select b from Booking b " +
А зачем для такого простого запроса SQL писать? Вы можете спокойно в названии метода уложиться и метод громоздко выглядеть не будет

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +
Лишняя пустая строка

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShortDto.java
> +    public BookingShortDto() {
А почему не через NoArgsConstructor от lombok?

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> -@RequestMapping(path = "/requests")
Зачем убираете? Над всеми методами префикс этот остается же

2022-11-23 17:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public UserDto() {
А почему не через NoArgsConstructor

2022-11-23 17:19 UTC, Frilock commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
А зачем меняете? Вы вроде с postres работаете в качестве основной БД, разве нет?

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Модификатор

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingDto bookingDto = new BookingDto(
Модификатор

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@Slf4j
Не вижу использования логгера

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@Transactional
Зачем транзакция над всеми методами?

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        } catch (EntityNotFoundException e) {
Не правильная обработка исключений в тестах. Смотрите, у мокито есть assertThrows и assertDoesNotThrow, 
Если хотите проверить что будет исключение используйте первую проверку. Кроме того, вы поймали исключение, еще бы было бы не плохо проверить его на нужное вам сообщение, чтобы точно убедиться, что произошла ожидаемая для Вас ошибка
Поправьте в других местах пожалуйста

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ObjectMapper mapper;
15 й спринт уже, а где то модификаторы не ставите. Почему? Вроде же кучу раз писалось и обсуждалось.

2022-11-23 17:19 UTC, Frilock commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +            ;
Лишний знак

2022-11-24 10:47 UTC, AleksKras commented on pom.xml
> +					<source>9</source>
странно, осознанно не менял. Даже интересно как изменение произошло. исправил

2022-11-24 10:49 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShortDto.java
> +    public BookingShortDto() {
Ошибся. в других местах поправил, здесь пропустил. исправлено

2022-11-24 10:52 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> -@RequestMapping(path = "/requests")
Словил ошибку, которая проявлялась на данном контроллере при проверке в ГИТе, и не проявлялась в идее. Перебирал все возможные варианты. Ошибку нашел, а эти неправильные изменения не откатил. Исправил

2022-11-24 10:52 UTC, AleksKras commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
Словил ошибку, которая проявлялась на данном контроллере при проверке в ГИТе, и не проявлялась в идее. Перебирал все возможные варианты. Ошибку нашел, а эти неправильные изменения не откатил

2022-11-24 10:53 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public UserDto() {
исправил.

2022-11-24 10:56 UTC, AleksKras commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ObjectMapper mapper;
жертва копипасты из теории. в теории в примере реализации схожего теста без модификатора :) 15й спринт уже - а в теории ошибки в примерах

2022-11-24 11:05 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(" select b from Booking b " +
не понимаю, как в названии указать поиск по связанной таблице. поиск же идет по UserID объекта Item, который связан с Booking.

2022-11-24 11:08 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findByBookerEquals(User user, Pageable pageable);
есть набор постмановских тестов, которые используют данные методы без параметров пагинации

2022-11-24 11:20 UTC, AleksKras commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                         @RequestParam(value = "state", required = false) Optional<String> state,
если null передать то Optional.isPresent() вернет false.
На мой взгляд, такая реализация вполне возможна, фактически обработка возможного null во входящих параметрах.

2022-11-24 11:31 UTC, AleksKras commented on pom.xml
> +					<source>9</source>
нашел в какой момент поменял. Идея в тестах не дает использовать List.of(...) без повышения версии, и автоматом предлагает поменять. странно, я думал что в 8й версии List.of должно работать

2022-11-24 20:32 UTC, AleksKras commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@Transactional
На мой взгляд аннотация @Transactional необходима, т.к. после каждого теста сгенерированные данные откатываются из БД. гарантии порядка запуска тестов нет, без отката есть вероятность влияния других тестов на результат

2022-11-24 20:33 UTC, AleksKras commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        } catch (EntityNotFoundException e) {
Спасибо. мне изначально казалось что я как-то коряво сделал. assertThrows не нашел сам. Круто, спасибо за помощь

2022-11-25 12:14 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findByBookerEquals(User user, Pageable pageable);
Честно говоря какая то странная ситуация выходит, то есть тесты постмана тестируют тот код который не используется. Получается так и это не логично. Может быть и вам для этих методов не стоило пагинацию делать?

2022-11-25 12:17 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ObjectMapper mapper;
Видимо тут примеры на "подумать" или разберись сам)

2022-11-25 12:20 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@Transactional
На мой взгляд откат делать через транзакцию плохая идея. Сделайте метод init(), пометьте его аннотацией BeforeEach (этот метод будет перед всеми другими исполняться) и в нем чистите БД. Кажется Ваша реализация через транзакцию проще и возможно даже быстрее, но это не очевидно и могут возникнуть проблемы

2022-11-25 13:02 UTC, Frilock requested changes
Добрый вечер, просьба в итоге вернуть 8ю версию в настройки, и я написал комментарий к Transactional в тестах, там лучше БД чистить через удаление данных в методе с аннотацией BeforeEach

2022-11-25 13:02 UTC, Frilock commented on pom.xml
> +					<source>9</source>
Все равно нужно, чтоб на 8й работало, давайте вернем. Если с List.of не получится используйте что нибуть другое.

2022-11-25 20:32 UTC, AleksKras commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@Transactional
Тогда получается противоречие с теорией, которая опубликована в рамках данного курса: 

"_Отметим ещё один важный момент. Если запустить приведённый выше тест и после этого посмотреть в тестовую базу данных, можно увидеть, что таблица users пуста. Обратите внимание на аннотацию @Transactional в начале теста. Она означает, что каждый тест будет запускаться в отдельной транзакции.
По умолчанию Spring откатывает каждую транзакцию в конце теста. Это нужно, чтобы не заполнять базу лишними тестовыми данными, которые могут помешать корректному исполнению тестов в дальнейшем_"

плюс в документации Spring
"_Annotating a test method with @Transactional causes the test to be run within a transaction that is, by default, automatically rolled back after completion of the test_"

т.е. это преимущество спринга, зачем от него отказываться?
при этом в документации спринга: 
_"Note that @Transactional is not supported on test lifecycle methods — for example, methods annotated with JUnit Jupiter’s @BeforeAll, @BeforeEach, etc."_

т.е. сделать @Transactional над методом @AfterEach нельзя, придется усложнять тест внедрением TransactionManager, ради очистки базы, которую спринг делает "из коробки" с помощью механизма транзакций. 
Предполагаю, откат транзакции работает быстрее чем очистка базы.

Без открытия транзакции попытка очистить таблицу в @AfterEach генерирует исключение:
javax.persistence.TransactionRequiredException: Executing an update/delete query

2022-11-26 10:48 UTC, Frilock approved these changes
Алексей, работу принял.

2022-12-02 15:16 UTC, merged