реализация ТЗ спринта 16
AleksKras/java-shareit pull request #4
Opened 2022-12-04 15:53 UTC by AleksKras

2022-12-04 21:34 UTC, Frilock requested changes
Добрый вечер, задача выполнена не до конца. В ваших контроллерах из подмодуля server должна пропасть валидация данных, это основной смысл задачи, чтобы валидация происходила в gateway. Ее также нужно убрать из pom файла server. Соответственно, тесты, которые тестировали данный функционал нужно перенести в подмодуль gateway.

2022-12-04 21:34 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +	private final ItemClient itemClient;
Съехало форматирование

2022-12-04 21:34 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    @PostMapping()
Пустые скобки можно не писать

2022-12-04 21:34 UTC, Frilock commented on server/pom.xml
> +        <dependency>
Мне кажется данная зависимость тоже должна быть убрана, по сути это ведь тоже валидация. Разве нет?

2022-12-05 13:16 UTC, AleksKras commented on server/pom.xml
> +        <dependency>
в рамках ревью одного из предыдущих спринтов было предложено использовать StringUtils.isNotBlank(), для этой функции и нужна зависимость. В валидации у меня не используется.

2022-12-06 06:52 UTC, Frilock approved these changes
Принято

2022-12-06 06:52 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        } else {
else не нужен, дальше же ведь нет кода, а внутри if законченные выражения

2022-12-06 06:52 UTC, Frilock commented on server/pom.xml
> +        <dependency>
Для StringUtils нужна jakarta.validation-api? По моему нет)

2022-12-06 06:52 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/booking/Booking.java
> -    @Future
На БД валидацию можно оставить было

2023-01-02 16:41 UTC, merged